CREATE TABLE refresh_tokens(
    tokenId CHAR(36) NOT NULL,
    tokenValue CHAR(64) NOT NULL,
    refreshTokenExpiration TIMESTAMP NOT NULL,
    userId CHAR(36) NOT NULL,
    userAgent VARCHAR(500) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_refresh_tokens PRIMARY KEY (tokenId),
    CONSTRAINT FK_refresh_tokens_users FOREIGN KEY (userId) REFERENCES users(userId) ON DELETE CASCADE
) ENGINE=InnoDB CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;